config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :support_messages, only: %i[new create]
  resources :badges, only: %i[index]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: %i[index show]
      end
    end

    resources :gists, only: %i[index]
    resources :badges, except: :show
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  enum rule_type: { x_attempt: 0, all_from_category: 1, elementary_of_category: 2 }

  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :name, :url, :rule_type, :rule_value, presence: true
  validates :rule_type, inclusion: { in: Badge.rule_types.keys,
                                     message: "'%{value}' is not a valid" }

  def self.select_box_values
    [
      [I18n.t('admin.badges.rule_type.x_attempt'), Badge.rule_types[:x_attempt]],
      [I18n.t('admin.badges.rule_type.all_from_category'), Badge.rule_types[:all_from_category]],
      [I18n.t('admin.badges.rule_type.elementary_of_category'),
       Badge.rule_types[:elementary_of_category]],
    ]
  end
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :find_badge, only: %i[edit update destroy]

  def index
    @badges = Badge.all
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)
    if @badge.save
      redirect_to admin_badges_path, notice: t('.success')
    else
      render :new
    end
  end

  def edit; end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def badge_params
    params.require(:badge)
        .permit(:name, :url, :rule_type, :rule_value)
        .tap{ |param| param[:rule_type] = param[:rule_type].to_i }
  end

  def find_badge
    @badge = Badge.find(params[:id])
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @user_badges = current_user.user_badges
  end
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td class="text-center"><%= badge.name %></td>
  <td class="text-center"><%= badge.url %></td>
  <td>
    <img src="<%= badge.url %>" width="189" height="255">
  </td>
  <td class="text-center">
    <%= link_to "Edit", edit_admin_badge_path(badge.id), class: "btn btn-secondary" %>
    <%= link_to 'Delete',
                admin_badge_path(badge),
                method: :delete,
                data: {confirm: 'Are you sure?'},
                class: "btn btn-secondary" %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |form| %>
  <%= render 'shared/form_errors', resource: @badge %>

  <p>
    <%= form.label :name %>
    <%= form.text_field :name, id: :badge_name %>
  </p>

  <p>
    <%= form.label :url %>
    <%= form.text_field :url, id: :badge_url %>
  </p>

  <p>
    <%= form.label :rule_type %>
    <%= form.select :rule_type, Badge.select_box_values %>
  </p>

  <p>
    <%= form.label :rule_value %>
    <%= form.text_field :rule_value, id: :badge_rule_value %>
  </p>

  <p><%= form.submit %></p>
<% end %>

app/views/admin/badges/edit.html.erb
<h1>Edit badge</h1>

<%= render 'form' %>
<%= link_to t('.back'), admin_badges_path %>

app/views/admin/badges/index.html.erb
<h1><%= t('.header') %></h1>
<div>
  <a><%= link_to t('.add_badge'), new_admin_badge_path, class: "btn btn-primary" %></a>
</div>
<table class="table">
  <tr>
    <th class="text-center"><%= t('.name') %></th>
    <th class="text-center"><%= t('.url') %></th>
    <th class="text-center"><%= t('.image') %></th>
    <th class="text-center"><%= t('.actions') %></th>
  </tr>
  <%= render @badges %>
</table>

app/views/admin/badges/new.html.erb
<h1>Add badge</h1>

<%= render 'form' %>
<%= link_to t('.back'), admin_badges_path %>