config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :support_messages, only: %i[new create]
  resources :badges, only: %i[index]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: %i[index show]
      end
    end

    resources :gists, only: %i[index]
    resources :badges, except: :show
  end
end

app/views/admin/_nav.html.erb
<table class="nav nav-admin">
  <tr>
    <% if user_signed_in? %>
      <th><a class="badge badge-pill badge-info" href="<%= root_path %>">Test Guru</a></th>
      <th><a class="badge badge-pill badge-info" href="<%= tests_path %>">Test Passage</a></th>
      <th><a class="badge badge-pill badge-info" href="<%= admin_gists_path %>">Gists</a></th>
      <th><a class="badge badge-pill badge-info" href="<%= admin_badges_path %>">Badges</a></th>

      <th>
        Welcome, <b><%= current_user.first_name %> <%= current_user.last_name %></b> Admin
      </th>
      <th>
        <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-secondary" %>
      </th>
    <% else %>
      <th>
        <%= link_to 'Login', new_user_session_path, class: "btn btn-primary" %>
      </th>
      <th>
        <%= link_to 'Signup', new_user_registration_path, class: "btn btn-primary" %>
      </th>
    <% end %>
  </tr>
</table>