config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :support_messages, only: %i[new create]
  resources :badges, only: %i[index]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: %i[index show]
      end
    end

    resources :gists, only: %i[index]
    resources :badges, except: :show
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :test_passages
  has_many :gists

  validates :body, presence: true

  def number
    test.questions.to_a.index(self) + 1
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  MIN_PERCENT_TO_BE_PASSED = 85

  belongs_to :test
  belongs_to :user
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :set_current_question

  def completed?
    time_elapsed || current_question.nil?
  end

  def accept!(answer_ids)
    if time_over?
      self.time_elapsed = true
    else
      self.correct_questions += 1 if correct_answer?(answer_ids)
    end
    save!
  end

  def total_questions
    self.test.questions.size
  end

  def passed?
    correct_percent >= MIN_PERCENT_TO_BE_PASSED
  end

  def correct_percent
    @correct_percent ||= calc_percent_correct_questions
  end

  def calc_percent_passage
    100 * count_passed_questions / total_questions
  end

  def time_over?
    created_at + test.timer.minutes < Time.current
  end

  def finish_timestamp
    (created_at + test.timer.minutes).strftime("%FT%T")
  end

  private

  def count_passed_questions
    test.questions.order(:id).where('id < ?', current_question.id).count
  end

  def set_current_question
    return unless test.present? # added to avoid err in IRB code

    self.current_question = if current_question.nil?
                              test.questions.first
                            else
                              next_question
                            end
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def correct_answer?(answer_ids)
    return false if answer_ids.nil?

    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def calc_percent_correct_questions
    correct_questions * 100 / total_questions
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :set_test_passage, only: %i[show update result gist]

  def show; end

  def update
    @test_passage.accept!(params[:answer_ids])
    if @test_passage.completed?
      @test_passage.update!(success: true) if @test_passage.passed?
      BadgeDistributorService.new(@test_passage).call
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def result; end

  def gist
    result = GistQuestionService.new(current_user, @test_passage.current_question).call
    flash_options = if result.respond_to? :html_url
                      { notice: t('.success_url', link: result.html_url) }
                    elsif result.success?
                      { notice: t('.success') }
                    else
                      { alert: t('.failure') }
                    end
    redirect_to @test_passage, flash_options
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def current_question_info(test_passage)
    current_question_number = test_passage.current_question.number
    "Question #{current_question_number} of #{test_passage.total_questions}:"
  end

  def result_message(test_passage)
    prefix = test_passage.passed? ? 'Success!' : 'Failed! Try again!'
    "#{prefix} #{test_passage.correct_percent}% question are correct."
  end

  def result_message_class(test_passage)
    "test_passage #{test_passage.passed? ? 'passed' : ' failed'}"
  end
end

app/views/test_passages/result.html.erb
<h><%= t('.header', title: @test_passage.test.title) %></h>

<% if @test_passage.time_elapsed? %>
  <p>Time over!</p>
<% end %>

<p class="<%= result_message_class(@test_passage) %>">Result: <%= result_message(@test_passage) %></p>

<%= link_to 'Back to list of tests', tests_path %>

app/views/test_passages/show.html.erb
<h>Passing the '<%= @test_passage.test.title %>' test </h>
<br>
<% percent_passage = @test_passage.calc_percent_passage %>
<div class="progress">
  <%= content_tag :div, "#{percent_passage}%",
                  class: %w(progress-bar progress-bar-info),
                  style: "width: #{percent_passage}%" %>
</div>
<br>
<p>Timer: <span id="countdown"></span></p>
<div id="passage_finish" class="hide"><%= @test_passage.finish_timestamp %></div>
<br>
<p><%= current_question_info(@test_passage) %></p>
<p><%= @test_passage.current_question.body %></p>
<br>
<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}"%>
      <%= b.label %>
    </p>
  <% end %>

  <p><%= link_to 'Gist question', gist_test_passage_path(@test_passage), method: :post %></p>
  <p><%= form.submit 'Next', id: "next" %></p>
<% end %>
<br>
<%= link_to 'Back to list of tests', tests_path %>