config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :support_messages, only: %i[new create]
  resources :badges, only: %i[index]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: %i[index show]
      end
    end

    resources :gists, only: %i[index]
    resources :badges, except: :show
  end
end

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="row d-flex justify-content-center">
    <%= content_tag :div, class: flash_class(key), role: "alert" do %>
      <%= message %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    <% end %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<br>
<br>
<br>
<hr align="left" width="600" size="4" color="#ff9900" />
<br>
<p>
  <%= current_year %> | Andrei K. |
  <a href="<%= github_url('the-action-man', 'tn-test-guru') %>" target="_blank">TestGuru</a>
</p>
<p>It is awesome application to create your own tests</p>
<p>Учебный проект в онлайн-школе <a href="http://thinknetica.com/" target="_blank">Thinknetica</a></p>

app/views/shared/_form_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
      <h2><%= t('.header', count: resource.errors.count) %></h2>

      <ul>
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  <% end %>
<% end %>

app/views/shared/_nav.html.erb
<table class="nav user">
  <tr>
    <th><a class="badge badge-pill badge-info" href="<%= root_path %>">Test Guru</a></th>
    <% if user_signed_in? %>
      <th><a class="badge badge-pill badge-info" href="<%= new_support_message_path %>">Contact</a></th>
      <th><a class="badge badge-pill badge-info" href="<%= badges_path %>">Badges</a></th>
      <th>
        Welcome, <b><%= current_user.email %></b> Guru
      </th>
      <% if current_user.admin? %>
        <th>
          <a class="badge badge-pill badge-info" href="<%= admin_tests_path %>">Admin panel</a>
        </th>
      <% end %>
      <th>
        <%= button_to 'Logout', destroy_user_session_path, method: :delete %>
      </th>
    <% else %>
      <th>
        <%= link_to 'Login', new_user_session_path %>
      </th>
      <th>
        <%= link_to 'Signup', new_user_registration_path %>
      </th>
    <% end %>
  </tr>
</table>